// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application"
import { Application } from "@hotwired/stimulus"
const application = Application.start()

// Eager load all controllers defined in the import map under controllers/**/*_controller
application.debug = false
window.Stimulus   = application

export { application }

// Lazy load controllers as they appear in the DOM (remember not to preload controllers in import map!)
// import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
// lazyLoadControllersFrom("controllers", application)
